apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "k-rsync.fullname" . }}-fpart"
  labels:
{{ include "k-rsync.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ include "k-rsync.fullname" . }}-fpart"
    spec:
      initContainers:
        - name: amqp-declare-queue
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/amqp-declare-queue
          args:
            - "--url=$(BROKER_URL)"
            - "--queue=$(QUEUE)"
          env:
            - name: BROKER_URL
              value: 'amqp://guest:guest@{{ include "k-rsync.fullname" . }}-message-broker:{{ .Values.rabbitmq.service.port }}'
            - name: QUEUE
              value: file.list.part.queue
      serviceAccountName: {{ template "k-rsync.serviceAccountName" . }}
      containers:
      - name: fpart-amqp-publish
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: "/srcd"
        command:
          - "/bin/bash"
        args:
          - "-c"
          - "fpart -v -L -f 10000 -zz -o /tmp/part.out . -W 'cat ${FPART_PARTFILENAME} | /usr/bin/amqp-publish --url=$(BROKER_URL) --routing-key=$(QUEUE)'"
        env:
          - name: BROKER_URL
            value: 'amqp://guest:guest@{{ include "k-rsync.fullname" . }}-message-broker:{{ .Values.rabbitmq.service.port }}'
          - name: QUEUE
            value: file.list.part.queue
        volumeMounts:
        - name: source
          mountPath: /srcd
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: OnFailure
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.source.claimName }}"
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "k-rsync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}