{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k-rsync.serviceAccountName" . }}
  labels:
{{ include "k-rsync.labels" . | indent 4 }}
{{- end -}}
